apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if or .Values.configs .Values.secrets }}
          env:
          {{- with .Values.secrets }}
          # Loop through all secrets under .Values.secrets
            {{- range $key, $value := .}}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  {{- range $subkey, $subvalue := .}}
                  name: {{ $subkey }}
                  key: {{ $subvalue }}
                  {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.configs }}
          # Loop through all configs under .Values.configs
            {{- range $key, $value := .}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  {{- range $subkey, $subvalue := .}}
                  name: {{ $subkey }}
                  key: {{ $subvalue }}
                  {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
          {{- with .Values.ports }}  
          ports:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              containerPort: {{ $value.containerPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
