{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "activemq.serviceAccountName" . }}
  labels:
    {{- include "activemq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- range $key, $value := .}}
- name: {{ $value }}
{{ end -}}
{{- end -}}
{{- with .Values.serviceAccount.secrets }}
secrets:
{{- range $key, $value := .}}
- name: {{ $value }}
{{ end -}}
{{- end -}}
{{- end -}}