{{- if .Values.privileged.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "privileged.name" }}
  annotations:
    {{- toYaml .Values.privileged.annotations | nindent 4 }}
  labels:
    {{- include "security.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.privileged.spec | nindent 2 }}
{{- end -}}