{{- if .Values.restricted.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "restricted.name" }}
  annotations:
    {{- toYaml .Values.restricted.annotations | nindent 4 }}
  labels:
    {{- include "security.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.restricted.spec | nindent 2 }}
{{- end -}}