{{- if .Values.restricted.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "restricted.name" }}
  labels:
    {{- include "security.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "restricted.name" }}
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- with .Values.restricted.serviceAccounts }}
{{- range $key, $value := . }}
- kind: ServiceAccount
  name: {{ $value }}
  namespace: {{ $key }}
{{ end -}}
{{- end -}}
{{- with .Values.restricted.groups }}
{{- range $key, $value := . }}
- kind: Group
  name: {{ $value }}
{{ end -}}
{{- end -}}
{{- end -}}