{{- if .Values.restricted.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restricted
roleRef:
  kind: ClusterRole
  name: restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- with .Values.restricted.serviceAccounts }}
{{- range $key, $value := . }}
- kind: ServiceAccount
  name: {{ $value }}
  namespace: {{ $key }}
{{ end -}}
{{- end -}}
{{- end -}}